language: node_js
node_js:
  - "node"
  - "6"
sudo: true
before_install:
  - npm i -g npm@3.10.10
cache:
  directories:
    - "node_modules"
install:
  - npm install
os:
  - windows
env:
  - NODE_ENV=development
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage